### ISSUE TITLE
Thunk middleware types gone from v1.6.0-alpha.2

### ISSUE THREAD

**Issue by mtodberg** [reduxjs/redux-toolkit#1070]
After upgrading to `@reduxjs/toolkit@next` version `@reduxjs/toolkit@v1.6.0-alpha.2`, the thunk types are not correctly added to the dispatch type anymore. Before there would be a `ThunkDispatch<CombinedState<...>>` in `AppDispatch` as in the following example.

```ts
import { configureStore } from '@reduxjs/toolkit';

export type AppDispatch = typeof store.dispatch;

export const store = configureStore({
  reducer: createRootReducer(history),
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      thunk: true, <-- doesn't make any difference if you enable this or remove it.
      serializableCheck: false,
      immutableCheck: false,
    }).concat(
      ...
    ),
});
```

**Comment by phryneas** [comment]
This should be resolved by making sure that you have only Redux 4.1.0 installed in your system. Unfortunately many package managers screw that step up and users regularly end up with 4.0.5 and 4.1.0 side-by side, which leads to the effect you are experiencing here.

**Comment by mtodberg** [comment]
It worked fine when I had:

```js
"redux": ^4.0.5",
"@reduxjs/toolkit": "^1.5.0",
```

Upgrading redux to `^4.1.0`, doesn't fix the issue. Any other idea what could be wrong?

**Comment by phryneas** [comment]
This does **not** concern your package.json which should not even contain `redux` - this is what actually ends up in your `node_modules` folder. Check your `package-lock.json`\`yarn.lock` files.
Most of the time, the problems could be resolved by
* uninstalling `redux`
* reinstalling/updating `@reduxjs/toolkit`, `react-redux` and `@types/react-redux` (and probably other packages you have the might have dependencies or peerDependencies to `redux`)

**Comment by mtodberg** [comment]
Removing `redux` from node_modules did the trick. Thank you 👍🏻
