### ISSUE TITLE
Add `upsertQueryData` functionality

### ISSUE THREAD

**Issue by chrisjagoda** [reduxjs/redux-toolkit#1720]
I have a use case where I would like to pass an additional parameter when calling an endpoint, where I do not want this additional parameter to be cached. The first parameter, args, would still be serialized as the cache key as normal.

Would it be possible to provide an additional field to pass some additional data when calling an endpoint via a hook/initiate? My use case is for calling a query endpoint with initiate.

Perhaps an additional optional parameter after options? Something like`extraArgs`, `noCacheArgs`, or `nonCacheableArgs`. I don't know if it makes sense have it on the options parameter, https://redux-toolkit.js.org/rtk-query/api/created-api/endpoints#initiate, but that would work too.

**Comment by chrisjagoda** [comment]
Specifically, my use case is to cache the result from a create api call in a different cache. I can do this, but it comes at the cost of having to override serializeQueryArgs, and having to have some additional logic in the providesTags field for postById.

If I could pass an additional parameter in postsClient.endpoints.postById.initiate, e.g. the response from createPost, I could see that I have that data in the queryFn for getById, and if so, return it, caching it, or if not, calling the api and cache it as normal.

`
import { createApi } from "@reduxjs/toolkit/query/react";
import posts from "some-api";
import { getByIdProvidesTags, getByIdQueryFn, mapClientResponse, serializeGetByIdArgs } from "./postsHelper";

export const POSTS = "posts";
export const POST_BY_ID = "postById";

const { get: getPosts, getById: getPostById, create: createPost, update: updatePost } = posts;

const postsApi = createApi({
    reducerPath: "posts",
    tagTypes: [POSTS, POST_BY_ID],
    baseQuery: ({ args, method }) => method(...args).then(mapClientResponse),
    serializeQueryArgs: serializeGetByIdArgs(POST_BY_ID),
    endpoints: (builder) => ({
        posts: builder.query({
            query: (args) => ({ args: [args], method: getPosts }),
            providesTags: (result, error, args) => [{ type: POSTS, id: JSON.stringify(args) }],
        }),
        postById: builder.query({
            queryFn: getByIdQueryFn(getPostById),
            providesTags: getByIdProvidesTags(POST_BY_ID),
        }),
        createPost: builder.mutation({
            query: (args) => ({ args: [args], method: createPost }),
            invalidatesTags: (result, error) => (error ? [] : [{ type: POSTS }]),
            onQueryStarted: (_args, { dispatch, queryFulfilled }) =>
                queryFulfilled.then(({ data }) => dispatch(postsClient.endpoints.postById.initiate(data))),
        }),
        updatePost: builder.mutation({
            query: (args) => ({ args: [args], method: updatePost }),
            invalidatesTags: (result, error) => (error ? [] : [{ type: POSTS }]),
        }),
    }),
});

export default postsApi;
export const { usePostsQuery, usePostByIdQuery, useCreatePostMutation, useUpdatePostMutation } = postsClient;
`

**Comment by phryneas** [comment]
Without the code for `getByIdQueryFn` and `serializeGetByIdArgs` and maybe a bit more in-depth explanation, I really have no idea what exactly you are trying to accomplish here, sorry.

Generally, no, that is not supported, and so far I have not seen a use case valid enough to add first-class support for it, as it is very uncommon, there are ways around it (although clumsy) and would probably lead to lots of bugs and unexpected behaviour for users: the serialized arg is the base for the decision "do we make another request?" and many people would wonder why, even if they changed an argument, no additional request would be made.

**Comment by chrisjagoda** [comment]
This is what those two functions look like.


```
// Serialize args for getById endpoints
// Use when calling getById endpoint by either the id or the passed object to map the id from passed object to serializedKey
export const serializeGetByIdArgs =
    (getByIdEndpointName: string) =>
    ({ endpointName, queryArgs }) =>
        `${endpointName}(${
            endpointName === getByIdEndpointName && isObject(queryArgs) ? queryArgs.id : JSON.stringify(queryArgs)
        })`;

// Call getById and cache response if id passed as args, or cache getById object if object passed as args
// Use when calling getById endpoint by either the id or with an object to cache the object based off its id instead of retrieving it and then caching it
export const getByIdQueryFn =
    (method) =>
    <T>(args, _api, _extraOptions, baseQuery): MaybePromise<QueryReturnValue<T, unknown, unknown>> =>
        isObject(args) ? { data: args } : baseQuery({ args: [args], method });

// Provide id as tag id if id passed as args, or provide object id as tag id if object passed as args
// Use when calling getById endpoint by either the id or with an object to map the id from from passed object to tag
export const getByIdProvidesTags = (tagName) => (result, error, args) =>
    [{ type: tagName, id: isObject(args) ? args.id : args }];
```

Essentially what I'm doing with them is handling the case where instead of passing the `id` to `postById` to retrieve the post by id (the usual case), I'm passing the entire post as the arg to cache it in `postById`, without actually making the call to retrieve it.

If I could pass an additional parameter to an endpoint, I could avoid having to override the methods, `serializeGetByIdArgs` and not have the extra logic to handle two different types of args (the id or the post) in `getByIdProvidesTags` and `getByIdQueryFn`.

Instead in `createPost` I could do something like:

```
createPost: builder.mutation({
            query: (args) => ({ args: [args], method: createPost }),
            invalidatesTags: (result, error) => (error ? [] : [{ type: POSTS }]),
            onQueryStarted: (_args, { dispatch, queryFulfilled }) =>
                queryFulfilled.then(({ data }) => dispatch(postsClient.endpoints.postById.initiate(data, undefined, { isCreatedPost }))),
        }),
```
and then `getByQueryFn` could look like so the endpoint `method` is only called when `isCreatedPost` is falsy.
```
export const getByIdQueryFn =
    (method) =>
    <T>(args, _api, _extraOptions, baseQuery, extraArgs): MaybePromise<QueryReturnValue<T, unknown, unknown>> =>
        extraArgs?.isCreatedPost ? { data: args } : baseQuery({ args: [args], method });
```

**Comment by chrisjagoda** [comment]
I can think of some additional cases where having a place to put args that aren't part of the cache key would be useful.

One might be if you needed to have different options when calling an endpoint. Perhaps something like having a different retry or backoff approach for an endpoint when called from one place, but not another.

These options would have to be passed to the endpoint conditionally, and to have them share a cache and do so is not easy.

**Comment by phryneas** [comment]
So in that specific use case... how should `provides` work? If invalidated, it would fire the same query and return the old value instead of fetching new, updated data from the server. Are you sure you don't just want to prime your cache with some data from another source?  
In that case, [cache management utilities](https://redux-toolkit.js.org/rtk-query/api/created-api/cache-management-utils) might be more useful.

As for different backoffs: imagine, two component are mounted with the same cache entry - but different backoffs. Which would win? And if the components mounted in a different order, or the first one rerendered after the second one rendered, which one would win then? Would it cause a request every time?  
Coordinating something like that is very complicated - even for built-in functionality like polling. Having it only on the endpoint is at least a bit more manageable.

**Comment by chrisjagoda** [comment]
Basically, there is one route to pass data to queries/mutations, that is through args. I want a backdoor to pass additional data, called extraArgs, with the distinction made clear that anything passed through this backdoor will not be subject to any of the rules/side effects of args.

Provides would still behave the same, my "backdoor" cached items should behave no different than one that is normally cached.

I looked into the cache management utilities and I couldn't really find any way to provide what I want. I want the posts cached by id as `args` in the rtk query api endpoint, but I want to be able to freely create new cache entries, without going through the process of calling the endpoint api to retrieve the data.

Really, even more to my point and more direct/useful would be a method like `postsClient.util.createQueryData(data.id, data)`, that I could call instead of `postsClient.endpoints.postById.initiate(data)`, in `createPost` -> `onQueryStarted`. However, I think there may be an issue opened for something like this.

Backoffs may be more complicated on further consideration.

**Comment by phryneas** [comment]
As far as I know, people have been using `patchQueryData​` with a patch in the form `[ { op: "replace", path: [], value: yourNewValue ]`  for that.

**Comment by chrisjagoda** [comment]
That doesn't work for my use case. `patchQueryData` will only update query data if there's already a cached entry. It won't create one if there's not one there.

**Comment by phryneas** [comment]
Fascinating, someone was reporting they were doing this. But yeah, looking at the code, it shouldn't work.

I guess sooner or later we will need a `upsertQueryData` functionality. I'm not a fan of it, because it will enable a lot of patterns people could use to hurt themselves, but I guess they'll find workarounds that are even more dangerous otherwise.

**Comment by chrisjagoda** [comment]
> I guess they'll find workarounds that are even more dangerous otherwise.

Indeed I will, haha. Thank you for taking the time to understand my problem.

**Comment by kasparkallas** [comment]
In my RTK-Query API slice, I have single entity queries and list queries and they both return same type of objects. When I do a list query then I would like to upsert the cache for single entity queries. So this feature would help out. :)

**Comment by joel1st** [comment]
Another potential use case:
With projects like Next.js - during SSR we may want to use cached API responses for endpoints that have largely static payloads. At the moment, if we want to use RTKQuery we're kind've out of luck as there isn't a nice way to insert this data without firing off a HTTP request. This results in some endpoints being much slower than they need to be. 

@phryneas can you think of a way around this that wouldn't require this `upsertQueryData` functionality?

**Comment by markerikson** [comment]
This is now available in https://github.com/reduxjs/redux-toolkit/releases/tag/v1.9.0-alpha.1 . Please try it out and let us know how it works!

**Comment by davidrhoderick** [comment]
@markerikson Thanks for this release, I'm excited to try it out!

So in my situation, we are sending a `cart_token`, which is our cache key, to our API but that token can be either an encoded one that generates a unique token OR it can be the unique token itself.  For example, if I send the API `__c__generatedToken==`, I'll receive `{data: {cart_token: `asdfghjkl12345` ...}}`.  Or I can send it `asdfghjkl12345` and get the same data.  That's why we want to de-duplicate this entry because the `__c__generatedToken==` is only used once at the beginning and up until now, we have been fetching from the API twice, once with the generation token and once with the unique token, just to fill the cache entry.

So here's my endpoint:

```
import { vrioApi } from '../vrioApi';

const extendedVrioApi = vrioApi.injectEndpoints({
  endpoints: (builder) => ({
    carts: builder.query<any, { cart_token: string }>({
      query: ({ cart_token }) => ({
        url: `carts/${cart_token}`,
        method: 'GET',
      }),
      transformResponse: (response) => ({
        ...(response as any),
        order: {
          ...(response as any).order,
          shipping_profile_id:
            (response as any).order.shipping_profile_id ?? '',
        },
      }),
      async onQueryStarted(_arguments, { dispatch, queryFulfilled }) {
        try {
          const { data } = await queryFulfilled;

          dispatch(
            extendedVrioApi.util.upsertQueryData(
              'carts',
              { cart_token: data.cart_token },
              data
            )
          );
        } catch {}
      },
    }),
  }),
  overrideExisting: true,
});

export const { useCartsQuery, useLazyCartsQuery } = extendedVrioApi;
```

When I run this, I get an infinite loop of the `onQueryStarted` function.  I can see that `data` is correct but it just loops forever and never gets to the next function.  Am I doing something wrong here?  Should I not add it to the `onQueryStarted` callback?

**Comment by markerikson** [comment]
Hmm. That... actually sorta makes sense, given how we implemented `upsertQueryData`.

We opted to implement it as a tweak to our existing "actually start this async request" logic. That runs the _entire_ standard request sequence, including dispatching actions...

and also the cache lifecycle methods.

You've got an `onQueryStarted`, in a `carts` endpoint, that is also _upserting_ into a `carts` endpoint. So, the initial actual request is going to run `onQueryStarted`, which is going to call `upsertQueryData`, which then triggers its _own_ `onQueryStarted`, which.... recurses.

I'm going to say this is probably a bug in the design and we'll have to rethink some of this behavior.

@phryneas , thoughts?

**Comment by phryneas** [comment]
I don't really get what you are trying to do here. The code updates the cache entry with the value it already just got?

**Comment by davidrhoderick** [comment]
@phryneas it's more like the cache key we initially use is for generating the cache key that we want to use thereafter:

1. The user hits a URL with `__c__asdfghjkl12345==` in the URL.
2. This is what we use to fetch the cart so we pass it as the argument to the query.
3. The API identifies this argument as one that _generates_ a unique `cart_token` and returns `data` with that.
4. The unique `cart_token` returned in `data` is what we want to continue referencing, so we also update the `cart_token` with the unique one when we've received.

If a user were to keep hitting the URL with `__c__asdfghjkl12345==` in it over and over again, they'd keep creating unique `cart_token`s and they'd never be able to mutate the cart and complete the order because it's not actually tied to data.

Walking you all through this it makes me wonder, if we can identify the generation token, would it be better to use a `mutation` to "create" the unique token with the `upsertQueryData` function?

**Comment by markerikson** [comment]
That seems reasonable to me, yeah

**Comment by phryneas** [comment]
Or at least you should check that the endpoint you want to update is not the endpoint that just has been updated - I mean, just compare the argument of the current query with the argument of the query you want to upsert.

**Comment by davidrhoderick** [comment]
@phryneas that seemed like the most streamlined approach so I tried it and I could get out of the infinite loop, so thanks for that!

However, I am still hitting the API for that `cart_token`.  Basically, when the `cart_token` in `data` differs from the one in the URL, I redirect to the one from `data`, which triggers a query for that one.  What I'm expecting `upsertQueryData` to do is to add that cache entry so when I change the URL, it just fetches the cached value.  Instead, it appears to be still trying to fetch it from the API i.e., I still get 2 query calls even though I should have a cache entry that I upserted already.

**Comment by phryneas** [comment]
Do you see `onQueryStarted` executing twice or two actual requests? 
`upsertQueryData` triggers the lifecycle methods as if a request would be made, that is intended. It doesn't really make a request though, but immediately resolves with the upserted data.

**Comment by davidrhoderick** [comment]
I'm hoping my use-case isn't super specific to the point where this isn't helpful but let me flesh out the application a bit more:

First of all, before I can even fetch the data from API, I need an `access_token`, which I've used standard Redux state to hold since it is easily accessible from within RTK Query i.e., I wrap the axios call for a custom query function with the necessary `access_token` header.

Therefore, I don't make the `useCartsQuery` call until I have an `access_token`, then I use `useLazyCartsQuery` to trigger it when I do.  Unfortunately, it'll take a bit of work to go around that check so I would like to avoid that unless you tell me this won't work with lazy queries.

After that lazy query, I compare the returned `cart_token` from the `data` with what's in the URL (this is a Next.js application so I use the `useRouter` hook to grab that).  Then I redirect to the proper Next.js dynamic route containing the `cart_token` from `data`.  For example, if I go to `http://localhost:3000/__c__asdfghjkl12345`, fetch the cart, and receive a new `cart_token = "newCartToken"`, I redirect to `http://localhost:3000/newCartToken`.  Then the application would check for an `access_token`, which we have from before, and immediately trigger the `useLazyCartsQuery` function to fetch the new data.  I call that with `cartsQuery({cart_token: 'newCartToken'}, true);` to prefer the cached value.

So the questions are:

1. Is using a lazy query going to work with `upsertQueryData`?
2. Could the redirect and unmounting + remounting components be clearing the cache somehow?

@phryneas in response to your question, I see the `onQueryStarted` running twice, although in the conditional for `upsertQueryData`, it only runs once.  On top of that, I see a second API request in the Firefox console to get the cart with the new token.  That second API request shouldn't be happening if we have it in the cache and I'm preferring that value with the lazy query, correct?

**Comment by davidrhoderick** [comment]
In the Redux Devtools, should I see two entries one fulfillment:
![image](https://user-images.githubusercontent.com/2300366/187275452-2af4ae70-376b-42c6-9194-1e5d10cc09b6.png)
I only ever see one then it tries to get a new one.

**Comment by davidrhoderick** [comment]
However, this is interesting:
![image](https://user-images.githubusercontent.com/2300366/187276403-30a3d9f2-4652-4e65-8788-de9041a42080.png)

I actually have it as a query in there at the bottom as the fastest one, I just can't seem to access it without pinging the API

**Comment by davidrhoderick** [comment]
Sorry for spamming, this is the entire lay of the land so you can see the issue:

![image](https://user-images.githubusercontent.com/2300366/187277319-1743dd19-d4ca-447b-be3b-7f09baa1a050.png)

Notice the fastest is still the one we upsert but somehow, it's also the slowest because it hits the API twice, which is evident by the two calls in the console below.

**Comment by phryneas** [comment]
I really can't follow, I'm sorry. Can you try to make a simpler reproduction of what you are getting there?

**Comment by davidrhoderick** [comment]
Sure so check out the following repo for the code (I tried to pare it down as much as possible while maintaining the core functionality that I'm having issues with):

[https://github.com/davidrhoderick/testing-upsertQueryData](https://github.com/davidrhoderick/testing-upsertQueryData)

You can also demo it at [https://testing-upsert-query-data.vercel.app/](https://testing-upsert-query-data.vercel.app/).  I tried to make a Codesandbox but this was easier to integrate with Next.js and Redux etc.

**Comment by phryneas** [comment]
I'll look a bit deeper tomorrow, but on first look it just looks like you have a page transition there and after that transition you start with an empty store again.

**Comment by davidrhoderick** [comment]
@phryneas Yea that page transition is probably the issue.  I've messed around with the Next.js-Redux SSR wrapper and it was kind of painful.  Could Redux Persist be a simpler solution in this case?  I think the app could benefit from persisting some amount of data.

Oof you should see the actual app, this is HUGELY pared down!  Maybe I'll see if I can reproduce the issue without the lazy query and that should remove a bunch of the `useEffect`s and probably still point to the page transition.

**Comment by davidrhoderick** [comment]
@phryneas I did a little bit more testing and I _think_ the issue is really with this RTK Query `upsertQueryData` call itself and not really caused by Next.js:

First of all, looking at the Next.js documentation on routing, they declare that [the state will not change between pages](https://nextjs.org/docs/api-reference/next/router#resetting-state-after-navigation) and that it should be done manually.  This should especially be the case [if shallow routing is used](https://nextjs.org/docs/routing/shallow-routing) as it was in my project.  Therefore, I added to my test repo the following:

1. There is now a new Redux slice added for `count`.  This is initialized at `0`.
2. Whenever `count`, `dispatch`, `cart_token`, or `cart` is changed (in a `useEffect` callback), `count` is logged to the console, then if `count === 0`, we increment it and log that `'state did not persist'` and if `count === 1`, we log to the console that `'state persisted'`.  Basically, we are checking if the state is changing between navigation and fetching the `cart`.

([Code is here again](https://github.com/davidrhoderick/testing-upsertQueryData))

If you check out the demo site again at https://testing-upsert-query-data.vercel.app/, you'll see the following output in the console:

![image](https://user-images.githubusercontent.com/2300366/187950696-d9f0b9c6-9116-46f9-a4bc-b8afbe78ff00.png)

Based on that, you can see that the Redux state is persisting just fine.  It's the RTK Query `updateQueryData` state that is not persisting for some reason.  Is there something I need to change to get it to work?  Why is it hitting the API a second time if we see that Redux state persists _and_ we can see the cache entry in the Redux Devtools?  In my opinion, this shows that it isn't working as expected.

**Comment by phryneas** [comment]
I tried to record a replay of this and look at it, but it's pretty much impossible with the build you have there. Could you maybe deploy a non-minified build with source maps?

**Comment by davidrhoderick** [comment]
@phryneas should be fixed now but I think you can clone my repo and try it locally if that helps.

**Comment by phryneas** [comment]
I'm sitting in a hotel room here, I don't want to get into full debug mode right now, just wanna take a peek :)

**Comment by phryneas** [comment]
It's not minified any more, but still missing sourcemaps: https://app.replay.io/recording/attempt-2--b300cabf-f245-4024-baa6-e1720cd6eecc?point=11033630824435957513959892366393734&time=4106&hasFrames=true

I'll try to click around a bit but I fear I won't see a lot. You might want to try the time-travel debugger, jump to that extra request and go back from there.

**Comment by davidrhoderick** [comment]
Oh sorry I forgot the sourcemaps generation.  I think it should work now.

**Comment by phryneas** [comment]
Still no source maps. But from what I can see, I think this is still to some extent a nextjs problem - the moment that `trigger` calls a second time, there is definitely not the cache entry in the state.

**Comment by phryneas** [comment]
Or, as you said, some persisting thing happening. But again, this is a weird edge case thing. It might make more sense to try this behaviour without next at first - just see if it works normally in a sane environment without page transition reload and whatever else could happen there that involves multiple different libraries.

**Comment by davidrhoderick** [comment]
Re:Sourcemaps, I'm not sure what's going on but I've configured Next.js to output them so if they aren't showing up, I guess that's another bug I have to report.  By the time that gets sorted, I hope you get a chance to check out the repo locally.

As for reproducing the issue without the redirect, before I go head and create another repo with just React.js, it should be sufficient to avoid the redirect and just trigger the lazy query again, right?  If lazy query should use the same logic as the non-lazy one for `upsertQueryData`, I can just call the trigger function when I receive the first request's data and it should use the upserted cache entry instead of querying the API again, correct?

I updated the demo to do just that.  [If you check out line 47](https://github.com/davidrhoderick/testing-upsertQueryData/blob/main/pages/%5Bcart_token%5D.js#L47) of the `[cart_token].js` file, there's a `useEffect` block with the `replace` routing call commented out and replaced with a `cartsQuery` trigger call.  This is resulting in the same behavior.

However, let's say you wanted a CRA version of this, I put one up [here](https://testing-upsert-query-data-react.vercel.app/).  In my haste, I may have introduced a variable but if that's causing the issue, then I think we've learned something.  The source code is [here](https://github.com/davidrhoderick/testing-upsertQueryData-react).

Basically, here's how it works:

1. For the Redux store, it's just the carts API call.  The only thing I'm worried about is a `transformResponse` call that I'm using to artificially return a different `cart_token` than what I'm querying.  Also, I am querying [this service](https://www.instantwebtools.net/fake-rest-api#read-airline-id), but maybe you have a better example.
2. The `App` just wraps the `Queries` component with the Redux store.
3. `Queries` calls the _non-lazy_ `carts` query with `{cart_token: "2"}`.
4. The `carts` query transforms the response from instantwebtools.net to add `cart_token: '3'`
5. When we have `data` from that query, we render `ChildQuery`, which will use the non-lazy `carts` query with the returned `cart_token` from above.
6. This _shouldn't_ cause an API call _but_ it does, as can be seen in the console.  It should also be instantaneously shown with the result from the first query if it's cached.
7. Just to be sure we were using a cached entry for the first call, I have another `ChildQuery` component that queries `{cart_token: "2"}`, like the first call, but it's delayed by 5 seconds from page load.  As you will see, this _doesn't_ result in an API call, so caching _is_ working, just not for `upsertQueryData`.

I'm not sure how you were all testing this but at least the way I understand it to work in these now 4 different examples, I cannot get the `upsertQueryData` to behave how I expect it.

**Comment by markerikson** [comment]
@davidrhoderick looking at this a bit, and one issue I see is that the CRA app isn't using `1.9.0-alpha.1` - it's using `1.8.5`

**Comment by markerikson** [comment]
@davidrhoderick looking at this a bit further, I'm split between "I think the app code is buggy" and "I think RTKQ is having more promise resolution issues".

I made a replay of this and annotated it with a couple comments:

https://app.replay.io/recording/rtk-issue-1720-upsertquerydata-cra--c46aa01f-5e43-4946-9266-f7c04dd3bb74?point=973555661031535832245224488305062&time=464.0095029239766&hasFrames=true#

What I'm seeing is that:

- `<ChildQuery cart_token="3">` renders
- This kicks off the initial request for data with `"3"`
- It's only when _that_ request resolves that the `upsertQueryData()` call runs because of `data.cart_token !== cart_token`, except that we just came _back_ with data for `"3"` already 

So as far as the _app_ code goes, `upsertQueryData` appears to be working right.  It's just that the app code is only triggering `upsertQueryData` when the cart token you care about is already back in the app... and the reason for that feels like RTKQ is waiting too long to run query lifecycles.

**Comment by markerikson** [comment]
So after talking it over with Lenz, we _think_ this is maybe expected behavior based on the nuances of Redux action dispatches, React re-renders, and promise resolutions:

The timeline seems to be roughly:

- response is received
  - transformed and dispatched
  - reducers process
  - subscribers run, queue updates
  - React batches and renders at the end _in the same event loop tick_
  - this includes running React effects
  - Promise resolve gets queued
- promise resolves in the _next_ event loop tick:
  - now the rest of that lifecycle function continues
  - but at that point there's already a request for token `'3'` in flight

![image](https://user-images.githubusercontent.com/1128784/188041008-3f7eb9aa-7a62-469e-8801-e0ce8898240f.png)

**Comment by phryneas** [comment]
Yeah... generally correct analysis and that's what would happen if it would upsert at all.. I gotta try a fix.

**Comment by phryneas** [comment]
Yeah.. here's a CSB circumventing the timing issue described above and with the fix from #2669:

https://codesandbox.io/s/quiet-flower-6smsce?file=/src/App.js

**Comment by davidrhoderick** [comment]
@markerikson Thanks for your analysis.  Sorry about the CRA repo, it was the end of the work day and I was sort of just trying to get something done quickly so I messed it up.  In the end, I was still getting the same response even if the correct RTK version, but you saw that.

@phryneas Thanks for that fix!  So basically, you are skipping the child query unless the parent query is successful, that way the timing lines up that the cache has the upserted data?  Very clever (I didn't know about that `skipToken` import).

I do utilize this cart query all over my project but maybe I could wrap this code with a custom hook just to ensure I can render the page with the first data and in the background, make the second query.

I'll give it a try and see if it works, thanks for your help!

**Comment by agusterodin** [comment]
Super looking forward to this functionality!

Before I create a minimal reproduction of a problem I am running into while trying this new feature out, let me know if I am potentially misusing it or misunderstanding its capabilities.

I am running `1.9.0-alpha.1`

``` 
<a
  onClick={async event => {
    event.preventDefault()
    await dispatch(alarmApiUtil.upsertQueryData('getAlarmMetadataById', id, metadata))
    router.push(`alarm/${id}`)
  }}
>
Link
</a>
```

Background: we have all the metadata for an individual "alarm" in our app ahead of time from the "alarm list" endpoint (used for the list of cards). Ideally since we already have this data I would like to prepopulate the cache so the user never sees a loading spinner other than the situation where initial page load is on an "alarm details" screen. 

If you scrub frame by frame on the video below you will see that for a millisecond the pre-populated data appears. Unfortunately it immediately disappears and the loading state appears. Ideally the loading boolean would never be true and if the newly fetched data differs from the pre-populated data, the data would just be updated but without ever going into "loading state".

Is that possible with this feature? It would be super nice to have! Is this just a bug since upsertQueryData is still in feature preview?

https://user-images.githubusercontent.com/10248395/188683991-1083cb84-639f-4cb8-bbc6-87ad8940bdd4.mov

**Comment by phryneas** [comment]
@agusterodin please try again with the CI build from https://github.com/reduxjs/redux-toolkit/pull/2669

**Comment by phryneas** [comment]
@davidrhoderick without code, generally hard to tell. upserting should happen almost immediately when you call that method - maybe 1 or 2 ticks later.

**Comment by joel1st** [comment]
What is the approach we should use to take advantage of this with SSR?

Here is a dumbed down example of what I'm trying to achieve:
![Screen Shot 2022-09-27 at 3 26 37 pm](https://user-images.githubusercontent.com/4032164/192439468-0ceab776-d0d3-4a38-aacc-2391bc2cd6f7.png)

It looks like `upsertQueryData` doesn't hydrate into the redux store during hydration (initiate call above does though):
![Screen Shot 2022-09-27 at 3 28 14 pm](https://user-images.githubusercontent.com/4032164/192439767-1d8df8e4-2a95-4baf-a4d3-3cd38911d0ef.png)

As a work around to the hydration problem, I tried removing the `return existingData;` so that initiate is called afterwards, with the expectation that the call to `initiate` would resolve instantly (as data should be in the cache due to the upsert), unfortunately this does not happen, and it fires off an API request regardless.

**Comment by joel1st** [comment]
I can confirm that updating the upsert implementation to 'subscribe: true' (and then unsubscribe afterwards) fixes the issue. 

As a design decision, Is this something that can be made configurable? Not entirely sure what the point of upsert is if you can really only update (I'm probably missing something).

**Comment by markerikson** [comment]
FYI I should hopefully be able to put out another 1.9.0 alpha tomorrow - got some other things I want to work on before I publish it.

**Comment by markerikson** [comment]
Just published https://github.com/reduxjs/redux-toolkit/releases/tag/v1.9.0-alpha.2 - please try it out and let us know if `upsertQueryData` is working right now!

**Comment by agusterodin** [comment]
Thanks good sir! Really hyped for upsert functionality.

I tried installing alpha 2 earlier today and one of my query hooks is acting weird. One of my query hooks is returning undefined data always despite response appearing completely normal in Chrome DevTools network tab. Other than the one broken query hook, all my other query hooks work fine. This issue is completely unrelated to upsert (haven't added anything related to upsert in my code just yet). 

Alpha 1 has this same weird issue of query hook not working. Downgrading to latest stable version causes everything to work perfectly again.

I will narrow it down and provide a repro tomorrow if it isn't some sort of trivial mistake.

**Comment by markerikson** [comment]
Hmm. We've definitely moved around a lot of internal pieces on the 1.9 branch, so it's entirely likely we borked something :)

Yeah, a repro/sandbox/replay would be very helpful!

**Comment by agusterodin** [comment]
The issue with the query hook only occurs on a page of mine that renders the page via SSR when that is the initial page you start using the website from. This is to make it so that the site doesn't break for web crawlers .

```
ViewerPage.getInitialProps = wrapper.getInitialPageProps(store => async ({ query, res }) => {
  const rawImageId = query.id
  const imageId = typeof rawImageId === 'string' ? parseInt(rawImageId) : NaN
  if (typeof window === 'undefined' && !isNaN(imageId)) {
    console.log('YOU LAUNCHED DIRECTLY FROM THIS PAGE SO USE SSR!')
    store.dispatch(imageApiEndpoints.getMetadata.initiate(imageId))
    await Promise.all(api.util.getRunningOperationPromises())
    const imageMetadataResponse = imageApiEndpoints.getMetadata.select(imageId)(store.getState())
    if (res && imageMetadataResponse.isError) res.statusCode = 404
  }
})
```

I can confirm that the console log statement only ever gets printed when you open the web app from this particular page (in NextJS). 

The query hook is still broken even if I comment all code within the getInitialPageProps function like this -> 

```
ViewerPage.getInitialProps = wrapper.getInitialPageProps(store => async ({ query, res }) => {
  // const rawImageId = query.id
  // const imageId = typeof rawImageId === 'string' ? parseInt(rawImageId) : NaN
  // if (typeof window === 'undefined' && !isNaN(imageId)) {
  //   console.log('YOU LAUNCHED DIRECTLY FROM THIS PAGE SO USE SSR!')
  //   store.dispatch(imageApiEndpoints.getMetadata.initiate(imageId))
  //   await Promise.all(api.util.getRunningOperationPromises())
  //   const imageMetadataResponse = imageApiEndpoints.getMetadata.select(imageId)(store.getState())
  //   if (res && imageMetadataResponse.isError) res.statusCode = 404
  // }
})
```

If I comment out the whole thing like this, my useBlaQuery hook works perfectly again ->

```
// ViewerPage.getInitialProps = wrapper.getInitialPageProps(store => async ({ query, res }) => {
//   const rawImageId = query.id
//   const imageId = typeof rawImageId === 'string' ? parseInt(rawImageId) : NaN
//   if (typeof window === 'undefined' && !isNaN(imageId)) {
//     console.log('YOU LAUNCHED DIRECTLY FROM THIS PAGE SO USE SSR!')
//     store.dispatch(imageApiEndpoints.getMetadata.initiate(imageId))
//     await Promise.all(api.util.getRunningOperationPromises())
//     const imageMetadataResponse = imageApiEndpoints.getMetadata.select(imageId)(store.getState())
//     if (res && imageMetadataResponse.isError) res.statusCode = 404
//   }
// })
```

Does this ring any immediate bells? Can you try pasting the snippet into one of the pages of your Next projects to see if your query hooks break as well?

```
ViewerPage.getInitialProps = wrapper.getInitialPageProps(store => async ({ query, res }) => {
  // intentionally blank
})
```

I'm not ruling out that my Redux setup/configuration isn't bum. Will create a reproduction if the issue doesn't immediately jump out at you after seeing this. About to do some meal prep for the week and then i'll hop back on to create that repro.

**Comment by agusterodin** [comment]
Btw, I commented out the getInitialProps stuff and tried upsert functionality. Upsert works exactly as expected! :D

**Comment by phryneas** [comment]
I'm gonna guess that if you have the `getInitialProps` in there, you have a hydration action and if you leave it out you don't have that hydration action 🤔 
Can you validate that? 

Can you take a look what exactly is modified in the state through that action?

**Comment by agusterodin** [comment]
Yes, only when getInitialProps is present does hydration action gets dispatched. If it is not present, no hydration action gets dispatched. Setting up reproduction now

<img width="602" alt="1" src="https://user-images.githubusercontent.com/10248395/194784632-c1ff9eff-0edb-4a16-92c7-29521d612c78.png">
<img width="597" alt="2" src="https://user-images.githubusercontent.com/10248395/194784633-c801ff03-881e-4b3d-9996-baf4df224655.png">
<img width="600" alt="3" src="https://user-images.githubusercontent.com/10248395/194784635-c2596ee6-5fd2-45b5-b8ef-5bbafaafb96e.png">
<img width="601" alt="4" src="https://user-images.githubusercontent.com/10248395/194784637-196b5e73-3713-4276-8777-97d88748c209.png">

**Comment by agusterodin** [comment]
Here is a minimal reproduction. For all I know I am not setting up Redux store properly to handle hydration. That being said, I'm surprised it worked in last stable version of RTK. I really appreciate the help!

https://github.com/agusterodin/redux-toolkit-1.9-alpha-ssr-bug-reproduction

**Comment by phryneas** [comment]
I had to do some changes to this to make it run at all for me (add node-fetch and abort-controller, change the api to reqres.in), but then it works on my system.

Could you maybe tweak this so it works on a CodeSandbox so that we really can both see the same behaviour?

**Comment by agusterodin** [comment]
Will do as soon as I get back home tonight.

Are you on a version of Node below 16? Mine works fine without the node-fetch and abort-controller dependencies.

Dumb move on my behalf not to just use a public mock API 😳

**Comment by agusterodin** [comment]
I just updated my reproduction repository to use reqres.in and pushed changes.

Unfortunately CodeSandbox isn't working properly and I can't create one (I keep getting an authorization error regardless of what I try)

<img width="1440" alt="Screen Shot 2022-10-11 at 6 46 34 PM" src="https://user-images.githubusercontent.com/10248395/195212678-99fd3a31-5180-4560-ab2b-cbbb667356ce.png">

 ***

This is the behavior I am experiencing when running locally. The data doesn't fetch if I start on the index page and click the link. The data does fetch if I start on the /image page (due to SSR doing its thing).

https://user-images.githubusercontent.com/10248395/195212895-6d6fc99e-6ef8-459f-8a0c-4b66a9644c4c.mov

I am on Node v16.13.0.

**Comment by agusterodin** [comment]
Were you able to recreate the issue with my updated issue reproduction repository? Is there anything else I can do to help with debugging?

**Comment by markerikson** [comment]
Honestly haven't had time to look at it.  My last couple evenings have been focused on the codemods for the `extraReducers` object syntax.

I may be able to take a look over the weekend.

**Comment by phryneas** [comment]
@agusterodin  You can just replace `github.com` with `githubbox.com` to get a working codeSandbox of this :)

https://codesandbox.io/s/github/agusterodin/redux-toolkit-1.9-alpha-ssr-bug-reproduction

I see the problem, investigating now.

**Comment by phryneas** [comment]
@agusterodin the problem here is a timing problem in combination with that hydrating reducer you are using. This works:
```diff
const reducer = (state, action) => {
  if (action.type === HYDRATE) {
+   const { api: _ignore, ...hydrate } = action.payload;
    const nextState = {
      ...state,
-      ...action.payload
+     ...hydrate
    }
    if (typeof window !== 'undefined' && state?.router) {
      nextState.router = state.router
    }
    return rootReducer(nextState, action)
  } else {
    return rootReducer(state, action)
  }
}
```

Generally, it is safer to have RTK Query do the rehydration for the api slice itself.

In this specific case, there is nothing to hydrate from the server. So that reducer overwrites the client state with `{}`. Unfortunately, at that point the client has already started a query - and that data gets lost.

I believe this might have something to do with a timing change that seems to have happened in a recent version of `next-redux-wrapper`: https://github.com/kirill-konshin/next-redux-wrapper/issues/493

**Comment by markerikson** [comment]
My takeaway from those last couple comments is that whatever @agusterodin was seeing isn't actually related to `upsertQueryData`, but rather `next-redux-wrapper`?

Given that, I'd like to close this issue for bookkeeping purposes.  If there is anything else going on, let's open up a new issue from here.

1.9-beta.0 is ready to go - I'm just going to wait until morning to publish and announce it.

**Comment by agusterodin** [comment]
> My takeaway from those last couple comments is that whatever @agusterodin was seeing isn't actually related to `upsertQueryData`, but rather `next-redux-wrapper`?
> 
> Given that, I'd like to close this issue for bookkeeping purposes. If there is anything else going on, let's open up a new issue from here.
> 
> 1.9-beta.0 is ready to go - I'm just going to wait until morning to publish and announce it.

Yes, my previously mentioned issue is 100% related to the next wrapper and ended up having nothing to do with RTK 1.9. Downgrading to wrapper v7 fixes the issue.

Upsert behavior works exactly as expected 🎉 Thanks for the incredible work!

**Comment by markerikson** [comment]
Suh-WEEEEET! 

Thank you for the fast response and for trying that out for us!

**Comment by davidrhoderick** [comment]
@phryneas @markerikson Just wanted to say thanks a lot for release 1.9.0!  It looks like it's working great on my application.  I had to do a couple things to get it working but they were necessary for my application:

1. @phryneas solution for checking whether the `cart_token` matches `data.cart_token` was important or I get a forever loop.  In my latest implementation, I forgot that at first and remembered the solution from before so it was necessary.  Might be good to put that in documentation if it's not there.
2. In my application, I had a parent component calling a lazy query to get the data.  Then in child components, I used a non-lazy query to get the data.  This actually caused me issues with a double-submit CSRF token & cookie where mid-flight requests would 403 because the CSRF token & cookie would change on SSR between redirects.  I used `useQueryState` instead of `useQuery` in those child components to defeat that issue and it reminded me to come back to de-duplicating the initial call.  Turns out, that's what was needed.

Plus the fact that you've now officially released this code as version 1.9.0, I have to say great job!
