### ISSUE TITLE
Middleware for RTK-Query API at reducerPath Error - "only" while running RTL tests

### ISSUE THREAD

**Issue by prabhasjoshi** [reduxjs/redux-toolkit#2796]
When defining the store for tests in React Testing Library - while working with RTK-query:

```
const rootReducer = combineReducers({
   users: userReducer,
   vpApi: vpApi.reducer 
})

const store = configureStore({
  reducer: rootReducer,
  middleware: [
    ...getDefaultMiddleware(),
    sagaMiddleware,
    vpApi.middleware,
  ],
});
```

This is giving an error while running RTL tests :

Warning: Middleware for RTK-Query API at reducerPath "vpApi" has not been added to the store.
Features like automatic cache collection, automatic refetching etc. will not be available.

the same code is being used in the mock store for tests and the real store for the application - the application is working fine - but the tests are giving an error.

I have tried all combination of providing middleware to configureStore and the the same key is present in the rootReducer also.

Please help

**Comment by markerikson** [comment]
@prabhasjoshi can you post a CodeSandbox or a repo that shows this problem happening?

**Comment by prabhasjoshi** [comment]
@markerikson @phryneas this is solved now.
have encapsulated all the details [here](https://stackoverflow.com/questions/74125530/middleware-for-rtk-query-api-at-reducerpath-error-only-while-running-rtl-tes/74205570#74205570)

**Comment by quicksilverr** [comment]
Hey, still getting this error...even after adding the middleware to the store

**Comment by phryneas** [comment]
@quicksilverr are you restoring some pre-initialized store?

**Comment by quicksilverr** [comment]
Hey, here's my store. 

```
import { configureStore } from '@reduxjs/toolkit';
import { localAppStorage } from './local-storage';
import { persistReducer, persistStore } from 'redux-persist';
import { Api } from '../api/root-api';
import { userSlice } from '../auth';
import { workspaceSlice } from '../workspace';
import appReducer from './appReducer';
import thunk from 'redux-thunk';
import { channelsSlice } from '../channels';
import { kycSlice } from '../kyc';
import { inviteSlice } from '../invite';
import { miscellaneousSlice } from '../miscellaneous';

const persistConfig = {
  key: 'root',
  storage: localAppStorage,
  whitelist: [
    userSlice.name,
    workspaceSlice.name,
    channelsSlice.name,
    kycSlice.name,
    inviteSlice.name,
  ],
  blacklist: ['messagesData', miscellaneousSlice.name],
};

const rootReducer = (state: any, action: any) => {
  if (action.type === 'userAuth/logOut') {
    return appReducer(undefined, action);
  }
  return appReducer(state, action);
};

const pReducer = persistReducer(persistConfig, rootReducer);
//@ts-ignore
const createDebugger = require('redux-flipper').default;

const reduxStore = configureStore({
  reducer: pReducer,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      immutableCheck: false,
      serializableCheck: false,
    }).concat(Api.middleware),
});

export type RootState = ReturnType<typeof store.getState>;
export const persistor = persistStore(reduxStore);
export const store = reduxStore;
export const dispatch = reduxStore?.dispatch;

```


and here's the api file

```
import {
  BaseQueryFn,
  createApi,
  FetchArgs,
  fetchBaseQuery,
  FetchBaseQueryError,
  FetchBaseQueryMeta,
} from '@reduxjs/toolkit/query/react';
import { store } from '../root/store';
import { getRefreshToken, getToken, logOut, onRefreshToken } from '../auth';
import { getConfigValue } from '@zonofi/shared';

interface RefreshTokenResponse {
  refreshToken: string;
  token: string;
}

export const REDUCER_PATH_ZONO_SELLER_API = 'zonoSellerApi';

const baseQuery = fetchBaseQuery({
  baseUrl: getConfigValue('API_ENDPOINT'),
  prepareHeaders: (headers) => {
    const accessToken = getToken(store.getState());
    if (accessToken) {
      headers.set('authorization', `Bearer ${accessToken}`);
    }
    return headers;
  },
});

export const baseQueryWithReauth: BaseQueryFn<
  string | FetchArgs,
  unknown,
  FetchBaseQueryError,
  any,
  FetchBaseQueryMeta
> = async (args, api, extraOptions) => {
  let result = await baseQuery(args, api, extraOptions);
  const refreshToken = getRefreshToken(store.getState());
  const accessToken = getToken(store.getState());

  if (result.error && result.error.status === 401) {
    const refreshResult = await baseQuery(
      {
        url: 'regenerate/token',
        method: 'POST',
        body: {
          refreshToken: refreshToken,
          token: accessToken,
        },
      },
      api,
      extraOptions
    );
    if (refreshResult.data) {
      const tokens: RefreshTokenResponse = refreshResult.data;
      api.dispatch(onRefreshToken(tokens));
      result = await baseQuery(args, api, extraOptions);
    } else {
      api.dispatch(logOut());
    }
  }
  return result;
};

export const Api = createApi({
  reducerPath: REDUCER_PATH_ZONO_SELLER_API,
  baseQuery: baseQueryWithReauth,
  endpoints: () => ({}),
  tagTypes: ['User', 'Payment'],
});

```

could you please explain a bit more on that, unable to understand? @phryneas

**Comment by phryneas** [comment]
@quicksilverr it seems that you did not add the api reducer?

**Comment by quicksilverr** [comment]
@phryneas But I have added it, in the combine reducers

```
import { combineReducers } from '@reduxjs/toolkit';
import { Api } from '../api/root-api';
//Other reducers

const messagesPersistConfig = {
  key: 'messages',
  storage: localAppStorage,
  blacklist: ['messages'],
};

const appReducer = combineReducers({
  [Api.reducerPath]: Api.reducer,
 ...Other reducers
});

export default appReducer;
```

**Comment by phryneas** [comment]
That's all a bit over the place :/

This should work, but could make probems with persistance (you are not blacklisting the apislice I think).

Could you maybe temporarily go back to a "normal" setup and slowly add things like persist back so you see what works and where you break it?

**Comment by quicksilverr** [comment]
> That's all a bit over the place :/
> 
> This should work, but could make probems with persistance (you are not blacklisting the apislice I think).
> 
> Could you maybe temporarily go back to a "normal" setup and slowly add things like persist back so you see what works and where you break it?

Hey @phryneas Sure, I'll simplify it. Just wanted to understand one more thing, is Default Middleware depreciated in 1.9.0?

**Comment by markerikson** [comment]
@quicksilverr : The _standalone_ version of `getDefaultMiddleware` has been deprecated for a while, because it doesn't end up with good TS types.

However, the version that you get inside of `configureStore` still works and is included:

```
configureStore({
  reducer,
  middleware: (getDefaultMiddleware) => {
    return getDefaultMiddleware().concat(otherMiddleware);
  }
})
```

**Comment by quicksilverr** [comment]
@markerikson I tried doing what @phryneas suggested, regarding removing persist and directly passing the rootReducer

```
const rootReducer = (state: any, action: any) => {
  if (action.type === 'userAuth/logOut') {
    return appReducer(undefined, action);
  }
  return appReducer(state, action);
};

const reduxStore = configureStore({
  reducer: rootReducer,
  middleware: (gDM) => gDM().concat(Api.middleware),
});
```

But still the error is there, can you please guide me a bit here. It's becoming a blocker for further development. I tried multiple things, but blocked here.

**Comment by markerikson** [comment]
@quicksilverr : sorry, not sure what else to tell you.  Can you put up a repo or a CodeSandbox that shows this actually happening, or make a Replay ( https://replay.io/record-bugs ) so that we can investigate it?

**Comment by quicksilverr** [comment]
Hey @markerikson Sure, will do that. I'll send the repaly recording.

**Comment by quicksilverr** [comment]
Hey @markerikson @phryneas One more thing wanted to add, we're currently using a dual store approach in our app, just for some migration purposes. 

We've followed the react context approach that is mentioned in the redux docs, for dual stores.

Should that create an issue for rtk query middleware?

**Comment by markerikson** [comment]
@quicksilverr no, because the error you're getting is part of the store creation process itself.

**Comment by phryneas** [comment]
It actually could - RTK Query will always try to use the "default" Redux store - if you created a new context and use your store with that other context, RTK Query will try to use the wrong store.

**Comment by markerikson** [comment]
OHHHHH, right - we do that check in the hooks themselves in addition to the thunks.  In which case yes, if the default store is not the one with the RTKQ setup, that _would_ end up throwing the error.

**Comment by quicksilverr** [comment]
Oh yes, that's great. Finally found the root cause of the issue. @markerikson @phryneas please could you tell is it possible to add certain kind of context in the api setup? Is there a way?

**Comment by markerikson** [comment]
@quicksilverr No, RTKQ does not currently have _any_ support for accessing an alternate `ReactReduxContext` or a second store. It only supports accessing the "standard" store, ie `<Provider store={store}>`.

**Comment by quicksilverr** [comment]
Okay, but the strange part is that, after dismissing the error, if you trigger the api call..it can be observed in the networks that the api call is happening. 

Can we make some tweaks in the middlewareWarning function in the base Initiate.ts file?

**Comment by markerikson** [comment]
@quicksilverr : I'm not sure what change you're requesting.  Can you clarify?

Technically, the thunks and reducer portions of RTKQ will run without the middleware...

but none of the cache lifetime or invalidation behavior will work, so RTKQ effectively breaks without the middleware being set up correctly.

**Comment by phryneas** [comment]
> Okay, but the strange part is that, after dismissing the error, if you trigger the api call..it can be observed in the networks that the api call is happening.

It will make requests and then not save the result in the store - because it has no store. 

> @quicksilverr No, RTKQ does not currently have any support for accessing an alternate ReactReduxContext or a second store. It only supports accessing the "standard" store, ie <Provider store={store}>.

Technically not true, you can create your own version of RTK Query `createApi`:
```js
const createApi = buildCreateApi(
  coreModule(),
  reactHooksModule({
    useDispatch: useSomeOtherDispatch,
    useSelector: useSomeOtherSelector,
    useStore: useSomeOtherstore
  })
)
```

But **please** don't do a dual store setup like this. You can just fine migrate within one store, no need for two of those!

**Comment by markerikson** [comment]
hah. right. I keep forgetting about that part! and I did see someone do that a few weeks ago too :)

**Comment by quicksilverr** [comment]
@phryneas @markerikson Thank you so much for your guidance.

```
const createApi = buildCreateApi(
  coreModule(),
  reactHooksModule({
    useDispatch: useSomeOtherDispatch,
    useSelector: useSomeOtherSelector,
    useStore: useSomeOtherstore
  })
)
```
ha, that's great. I wasn't aware that we can take this approach. I'll try this, and let you know...if this can work.
I genuinely understand and support that we should, never take the dual store approach. In our case, we have a mono-repo, with multiple apps. The old version of a web app, is talking to a different configured store and the new version is talking to the rtk store. 

So, in process of migration, we have to take this hard route of having dual stores, for migrating in batches.
