### ISSUE TITLE
Invalidates Tags Not Working

### ISSUE THREAD

**Issue by iamvaibhavrai** [reduxjs/redux-toolkit#4236]
Hey, I am using openapi to genetate the api endpoints. After the file is generated, I made changes to add the tagTypes, ProvideTags, and InvalidatesTags so deal with the caching.

<img width="558" alt="Screenshot 2024-02-23 at 4 45 37 PM" src="https://github.com/reduxjs/redux-toolkit/assets/6650437/9361cb6d-5b6e-425e-a7d8-6de5551939d2">

I am using enhanceEndpoint to add the tag type, and then used provideTags where I am fetching the details of the user and using invalidatesTags while fetching the list of users.

Let me tell you how is the workflow. First I fetch the list of user (so using /list/users/ api) which has invalidatesTags value of 'refund', and then when you click on the user, it is supposed to call /get/user api, which has providesTags.

Ideally, this should now fetch fresh data instead of serving data from the disk-cache, but this is still fetching data from the disk cache. I am confused what I am doing wrong. 

![image](https://github.com/reduxjs/redux-toolkit/assets/6650437/a3446e5d-914b-48a0-b639-d161990225f3)

**Comment by Ajmal0197** [comment]
In my case also **invalidateTags** are not working:
On **createCart**; **getCarts** is not called.

Libs Versions:
```
    "react-redux": "^9.1.0",
    "redux": "^5.0.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^3.1.0"
   ```

```
/* eslint-disable no-nested-ternary */
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

// Define an API slice using RTK Query
export const rtkBaseUrl1Api = createApi({
  reducerPath: 'rtkBaseUrl1Api',
  baseQuery: fetchBaseQuery({ baseUrl: 'https://dummyjson.com/carts' }),
  tagTypes: ['Cart', 'CartById', 'UNAUTHORIZED', 'UNKNOWN_ERROR'], 
  endpoints: (builder) => ({
    getCarts: builder.query({
      query: () => `/`,
      providesTags: ['Cart'],
    }),

    createCart: builder.mutation({
      query: (body) => ({
        url: '/add',
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body,
      }),
      invalidatesTags: ['Cart'], 
    }),

  }),
});

// Export hooks for usage in React components
export const {
  useGetCartsQuery,
  useCreateCartMutation,
} = rtkBaseUrl1Api;

```

**Comment by phryneas** [comment]
I'd assume both of you forgot to add the middleware to the store? It's hard to say without seeing this run.

**Comment by Ajmal0197** [comment]
> I'd assume both of you forgot to add the middleware to the store? It's hard to say without seeing this run.

Hi, this is my repo: https://github.com/Ajmal0197/RNDevLearnNew/tree/main/src/srcReduxToolkit/reduxRTKQuery

Apis are working fine just invalidateCache not working for me

**Comment by phryneas** [comment]
@Ajmal0197 this might have to do with your persistence setup. You'd need more setup than that to persist an api slice, so it probably keeps subscriptions from prior application starts. Blacklist the api slices and see if it makes a difference.

**Comment by Ajmal0197** [comment]
> @Ajmal0197 this might have to do with your persistence setup. You'd need more setup than that to persist an api slice, so it probably keeps subscriptions from prior application starts. Blacklist the api slices and see if it makes a difference.

TYSM; fixed now.

Soln ref: https://github.com/Ajmal0197/RNDevLearnNew/commit/71fd38facce4c4118d1ca5e40930259bfda59c6f

**Comment by iamvaibhavrai** [comment]
<img width="516" alt="Screenshot 2024-03-04 at 11 22 59 AM" src="https://github.com/reduxjs/redux-toolkit/assets/6650437/1c78587d-9d0d-46ca-8da6-f60b7ec351a2">

I am not using redux-persist or any other library for locally storing data, also I have used the middleware but it isn't working.

Let me know if you need any more infor @phryneas

**Comment by phryneas** [comment]
@iamvaibhavrai You might be clobbering your store here. 
If all of these are the same api (injecting doesn't create a new api, it's still the same one!), add it's middleware (and reducer!) only once to your store.  
If they are actually distinct apis (different calls to `createApi`): that should probably just be one api - we don't recommend having a lot of different apis (e.g. because validation over api boundaries is not a thing).

**Comment by n0one42** [comment]
I have also a strange problem with the `codegen-openapi`.
One of the generations is working fine and the other does not by the filterEndpoints.

Config file:
```cts
// https://redux-toolkit.js.org/rtk-query/usage/code-generation
import type { ConfigFile } from '@rtk-query/codegen-openapi';

const config: ConfigFile = {
	schemaFile:
		'mypath\\backend\\src\\Web\\wwwroot\\api\\specification.json',
	apiFile: 'src/app/store/apiService',
	apiImport: 'apiService',
	outputFiles: {
		'fullApi.ts': {},
		'CompanyManagementApi.ts': {
			filterEndpoints: [/Companies/i],
			exportName: 'CompanyManagementApi'
		},
		'FinancialFilesApi.ts': {
			filterEndpoints: [/FinancialFiles/i],
			exportName: 'FinancialFilesApi'
		}
	},
	hooks: true,
	tag: true
};

export default config;
```
specification.json -- NSwag generated
```json
...
  "paths": {
    "/api/Companies": {
      "post": {
        "tags": [
          "Companies"
        ],
        "operationId": "CreateCompany",
        "requestBody": {
          "x-name": "command",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCompanyCommand"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "integer",
                  "format": "int32"
                }
              }
            }
          }
        }
      }
    },
    "/api/FinancialFiles": {
      "post": {
        "tags": [
          "FinancialFiles"
        ],
        "operationId": "UploadFinancialFiles",
        "parameters": [
          {
            "name": "financialFileType",
            "in": "query",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/FinancialFileType"
            },
            "x-position": 1
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "files": {
                    "type": "array",
                    "nullable": true,
                    "items": {
                      "type": "string",
                      "format": "binary"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    },
...
```
FinancialFilesApi.ts which is correct:
```ts
import { apiService as api } from 'src/app/store/apiService';

export const addTagTypes = ['FinancialFiles'] as const;
const injectedRtkApi = api
	.enhanceEndpoints({
		addTagTypes
	})
	.injectEndpoints({
		endpoints: (build) => ({
			uploadFinancialFiles: build.mutation<UploadFinancialFilesApiResponse, UploadFinancialFilesApiArg>({
				query: (queryArg) => ({
					url: `/api/FinancialFiles`,
					method: 'POST',
					body: queryArg.body,
					params: { financialFileType: queryArg.financialFileType }
				}),
				invalidatesTags: ['FinancialFiles']
			})
		}),
		overrideExisting: false
	});
export { injectedRtkApi as FinancialFilesApi };
export type UploadFinancialFilesApiResponse = unknown;
export type UploadFinancialFilesApiArg = {
	financialFileType: FinancialFileType;
	body: {
		files?: Blob[] | null;
	};
};
export type FinancialFileType = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
export const { useUploadFinancialFilesMutation } = injectedRtkApi;
```
CompanyManagementApi.ts which is wrong:
```ts
import { apiService as api } from "src/app/store/apiService";
export const addTagTypes = [] as const;
const injectedRtkApi = api
  .enhanceEndpoints({
    addTagTypes,
  })
  .injectEndpoints({
    endpoints: (build) => ({}),
    overrideExisting: false,
  });
export { injectedRtkApi as CompanyManagementApi };
export const {} = injectedRtkApi;
```
The `addTagTypes` is missing.
It had should be `export const addTagTypes = ['Companies'] as const;`

For testing purposes, I added to my config also the export of the entire api and this one is complete and correct. And that is strange.
fullApi.ts
```ts
import { apiService as api } from 'src/app/store/apiService';

export const addTagTypes = [
	'Companies',
	'FinancialFiles',
] as const;
const injectedRtkApi = api
	.enhanceEndpoints({
		addTagTypes
	})
	.injectEndpoints({
		endpoints: (build) => ({
			createCompany: build.mutation<CreateCompanyApiResponse, CreateCompanyApiArg>({
				query: (queryArg) => ({
					url: `/api/Companies`,
					method: 'POST',
					body: queryArg.createCompanyCommand
				}),
				invalidatesTags: ['Companies']
			}),
			uploadFinancialFiles: build.mutation<UploadFinancialFilesApiResponse, UploadFinancialFilesApiArg>({
				query: (queryArg) => ({
					url: `/api/FinancialFiles`,
					method: 'POST',
					body: queryArg.body,
					params: { financialFileType: queryArg.financialFileType }
				}),
				invalidatesTags: ['FinancialFiles']
			}),
```

Any Idea why this happens? Atm I have to manually copy paste it from the fullApi.ts

**Comment by Shemrock3267** [comment]
Simple answer for cases when you receive an array of objects with some data, and they hold unique ids then you should probably provide those ids like so:

```ts
...
    getLeadsDatabase: {
      providesTags: result =>
        result?.data?.map(({ leads_id }) => {
          return { type: Tag.DB_LEADS, id: leads_id };
        }) || [{ type: Tag.DB_LEADS }],
    },
    purchaseLeads: {
      invalidatesTags: () => {
        return [{ type: Tag.DB_LEADS }, { type: Tag.BILLING }];
      },
    },
...
```

This was the fix for me. It works for representing lists of data in tables on just rows of cards, etc.

**Comment by JJPell** [comment]
Just in case anyone else has this issue, make sure that your `providesTags` & `invalidatesTags` properties are outside of your query.

Wrong ❌
```
	query: (queryArg) => ({
		url: `/api/FinancialFiles`,
		method: 'POST',
		body: queryArg.body,
		params: { financialFileType: queryArg.financialFileType }
		invalidatesTags: ['FinancialFiles']
	}),			
```

Correct ✅
```
	query: (queryArg) => ({
		url: `/api/FinancialFiles`,
		method: 'POST',
		body: queryArg.body,
		params: { financialFileType: queryArg.financialFileType }
	}),
	invalidatesTags: ['FinancialFiles']
```
